{% set name = "peepdb" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/peepdb-{{ version }}.tar.gz
  sha256: 10c8af8b1b552408175d6d163975bb7ed0f54d3d74e3ea29fd45438a07e456f0

build:
  entry_points:
    - peepdb=peepdb.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - mysql-connector-python >=9.0.0
    - psycopg2-binary >=2.9.9
    - pymysql >=1.1.1
    - cryptography >=43.0.0
    - tabulate >=0.8.9
    - click >=8.0.0
    - mariadb
    - cachetools >=5.5.0
    - keyring >=25.4.1
    - pymongo ==4.9.1
    - dnspython ==2.6.1

test:
  imports:
    - peepdb
  commands:
    - pip check
    - peepdb --help
  requires:
    - pip

about:
  home: https://github.com/evangelosmeklis/peepdb
  summary: A quick database table viewer
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
