{% set name = "peepdb" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/peepdb-{{ version }}.tar.gz
  sha256: 87a01c6fa7ef726063f6953b91fbf8e27c980c3229243f19fb407c489f037748

build:
  entry_points:
    - peepdb=peepdb.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - mysql-connector-python >=9.0.0
    - psycopg2-binary >=2.9.9
    - pymysql >=1.1.1
    - cryptography >=43.0.0
    - tabulate >=0.8.9
    - click >=8.0.0
    - mariadb

test:
  imports:
    - peepdb
  commands:
    - pip check
    - peepdb --help
  requires:
    - pip

about:
  home: https://github.com/evangelosmeklis/peepdb
  summary: A quick database table viewer
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
